name: Tests

on: [push, pull_request]

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cuda
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --tests

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.5.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test regular features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p pyrin-miner

      - name: Run cargo test no asm
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p pyrin-miner --features=no-asm


      - name: Run cargo test no parking_lot
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p pyrin-miner --no-default-features

      - name: Run cargo test shuttle
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p pyrin-miner --no-default-features --features=shuttle

      - name: Run cargo test for kaspaopencl
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p kaspaopencl


  test-release:
    name: Test Suite Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.5.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test release regular features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release -p pyrin-miner

      - name: Run cargo test release no asm
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=no-asm --release -p pyrin-miner

      - name: Run cargo test release no parking_lot
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --release -p pyrin-miner

      - name: Run cargo test release shuttle
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features=shuttle --release -p pyrin-miner

      - name: Run cargo test for kaspaopencl
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release -p kaspaopencl

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install cuda
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}


      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests -- -D warnings
