name: Build and upload assets
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Build gnu-linux on ubuntu-18.04 and musl on ubuntu latest
        os: [ ubuntu-18.04, windows-latest, macos-latest ]
        features: ["default", "pyrincuda/overclock "]
    name: Building, ${{ matrix.os }} ${{ matrix.features }}
    steps:
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.5.1'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Build on Linux GNU
        if: matrix.os == 'ubuntu-18.04'
        # We're using musl to make the binaries statically linked and portable
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release --all --features ${{ matrix.features }}
          feature_name=${{ matrix.features }}
          asset_name="pyrin-miner-${{ github.event.release.tag_name }}-${feature_name/\//-}-linux-gnu-amd64"
          strip ./target/x86_64-unknown-linux-gnu/release/pyrin-miner
          mkdir ${asset_name}
          mv ./target/x86_64-unknown-linux-gnu/release/pyrin-miner ${asset_name}/${asset_name}
          mv ./target/x86_64-unknown-linux-gnu/release/libpyrin*.so ${asset_name}/
          tar czvf ${asset_name}.tgz ${asset_name}
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV


      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cargo build --target=x86_64-pc-windows-msvc --release --all --features ${{ matrix.features }}
          feature_name=${{ matrix.features }}
          asset_name="pyrin-miner-${{ github.event.release.tag_name }}-${feature_name/\//-}-win64-amd64"
          mkdir ${asset_name}
          mv ./target/x86_64-pc-windows-msvc/release/pyrin-miner.exe ${asset_name}/${asset_name}.exe
          mv ./target/x86_64-pc-windows-msvc/release/pyrin*.dll ${asset_name}/
          bash ./integrations/windows/create_bat.sh ${asset_name}
          7z a -tzip -r ${asset_name}.zip ${asset_name}
          echo "archive=${asset_name}.zip" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.zip" >> $GITHUB_ENV

      - name: Build on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --target=x86_64-apple-darwin --release -p pyrin-miner
          asset_name="pyrin-miner-${{ github.event.release.tag_name }}-cpu-only-osx-amd64"
          mkdir ${asset_name}
          mv ./target/x86_64-apple-darwin/release/pyrin-miner ${asset_name}/${asset_name}
          tar czvf ${asset_name}.tgz ${asset_name}
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV


      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ env.archive }}"
          asset_name: "${{ env.asset_name }}"
          asset_content_type: application/zip

  intergrations:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        # Build gnu-linux on ubuntu-18.04 and musl on ubuntu latest
        itegration: [ hiveos ]
    name: Integrating, ${{ matrix.itegration }}
    steps:
      - name: Fix LibOpenCL on Linux
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Check out code into the module directory
        uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.2.2'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Build ${{ matrix.itegration }} Script
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release --all
          binary_name="pyrin-miner-${{ github.event.release.tag_name }}-linux-gnu-amd64"
          asset_name="pyrin-miner-${{ matrix.itegration }}"
          strip ./target/x86_64-unknown-linux-gnu/release/pyrin-miner
          mkdir pyrin-miner
          mv ./target/x86_64-unknown-linux-gnu/release/pyrin-miner pyrin-miner/${binary_name}
          mv ./target/x86_64-unknown-linux-gnu/release/libpyrin*.so pyrin-miner/
          bash integrations/${{ matrix.itegration }}/build.sh "${{ github.event.release.tag_name }}" "${binary_name}" pyrin-miner 
          echo "archive=${asset_name}.tgz" >> $GITHUB_ENV
          echo "asset_name=${asset_name}.tgz" >> $GITHUB_ENV

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ env.archive }}"
          asset_name: "${{ env.asset_name }}"
          asset_content_type: application/zip
